### ISSUE TITLE
[Bug] : Get Started and Login button are not working.

### ISSUE THREAD

**Issue by BaibhavTiwari** [ManishBisht777/courseify#13]
### Description
On clicking the Get Started and login buttons on the landing page, it shows `404 Page Not Found`.
I have posted the Screen shot below take a look.

### Screenshots

![image](https://user-images.githubusercontent.com/75496387/235364249-00cff3e2-c449-42f1-bb6c-1781d9cf006b.png)

**Comment by ManishBisht777** [comment]
Thanks for reminding @BaibhavTiwari
- currently, we don't have a Login page so the url can be replcae by `"/"`
- url on getting started will be `/docs` instead of `auth/docs`

**Comment by ManishBisht777** [comment]
wanna work on this?

**Comment by AshwanthramKL** [comment]
@ManishBisht777 I'd like to work on this issue.

**Comment by ManishBisht777** [comment]
@AshwanthramKL sure assigned to you

**Comment by BaibhavTiwari** [comment]
> wanna work on this?

ya sure why not.

**Comment by ManishBisht777** [comment]
> > wanna work on this?
> 
> ya sure why not.

sorry @BaibhavTiwari this is assigned to @AshwanthramKL as he ask first

you can look for another issue 
eg- #16
