### ISSUE TITLE
Enhancement: Add Hover Effect to  Features Section.

### ISSUE THREAD

**Issue by Saurav-Pant** [ManishBisht777/courseify#14]
### What would you like to share?

I noticed that there is no hover effect on the Features Section boxes, and I would like to suggest adding one. A hover effect would enhance the user experience by providing visual feedback when hovering over an element. This would make it easier for users to interact with the page.
if yes I want to work on it

**Comment by ManishBisht777** [comment]
thanks for raising an issue @Saurav-Pant, As the features section is just plain information so there is no need to add animations to it, doing so will make it interactive, and making a non-interactive element interactive will result in bas user Experience.
- however, we can add animations to other interactive elemens 

Feel free to mention those if you find them :)

**Comment by Saurav-Pant** [comment]
Thanks, but I think all interactive elements have enough animation
