### ISSUE TITLE
[Feat] Custom 404 Page

### ISSUE THREAD

**Issue by ManishBisht777** [ManishBisht777/courseify#16]
### Description

We can have a custom 404 Page for website instead of a default one

**Comment by BaibhavTiwari** [comment]
Assign this to me @ManishBisht777

**Comment by ManishBisht777** [comment]
Sure @BaibhavTiwari assigned to you

**Comment by Devansh-365** [comment]
If this issue is still open can you assign this to me?

**Comment by ManishBisht777** [comment]
Due to inactivity, this issue is assigned to @Devansh-365

**Comment by ManishBisht777** [comment]
Assigned to you @Devansh-365 :)
