### ISSUE TITLE
Typo in Website Header

### ISSUE THREAD

**Issue by AshwanthramKL** [ManishBisht777/courseify#19]
### Description

The website header is misspelt as "Crouseify" instead of "Courseify"

### Screenshots

![image](https://user-images.githubusercontent.com/71945723/235474820-6a6672c2-8dff-4bb1-b194-f981f79d9e6a.png)

**Comment by ManishBisht777** [comment]
good find @AshwanthramKL

**Comment by ManishBisht777** [comment]
let me know if you want to work on this

**Comment by AshwanthramKL** [comment]
Sure. But could you tell me where the <Head> is located?

**Comment by ManishBisht777** [comment]
It is present in `app/(pages)/layout.tsx` you can find a metadata there you can change its content
