### ISSUE TITLE
Not redirecting to discord page

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [ManishBisht777/courseify#23]
### Screenshots

![2023-05-06](https://user-images.githubusercontent.com/71914071/236613748-f267afa7-9c4f-402b-8be0-3dd0ab600283.png)

**Comment by ManishBisht777** [comment]
@SoundaryaKoutharapu Thanks for pointing this out currently we don't have a Discord server

Maybe we can hide the button for until we got a server

**Comment by AshwanthramKL** [comment]
Hey, I'd like to work on this. Can I?

**Comment by ManishBisht777** [comment]
> Hey, I'd like to work on this. Can I?

sure assigned to you
