### ISSUE TITLE
[Feat] Adding Husky and Prettier for Code Quality and Formatting

### ISSUE THREAD

**Issue by Devansh-365** [ManishBisht777/courseify#27]
### Description

I propose adding Husky and Prettier to the project as development dependencies. Husky will enable us to automate pre-commit and pre-push hooks, ensuring code quality and formatting standards are maintained consistently. Prettier, when integrated with Husky, will automatically format the codebase according to a predefined style guide.

### Some benefits: 
1) **Consistent Code Style**: Husky and Prettier will enforce a consistent code style across the project, reducing code review overhead and enhancing readability.

2) **Time-Saving**: By automating code formatting, developers can focus more on writing code rather than manually formatting it, leading to increased productivity.

3) **Error Prevention**: Pre-commit hooks can be configured to run linters, unit tests, or any other relevant checks, catching potential issues before they get committed.

4) **Collaboration**: Standardized formatting and code quality practices foster better collaboration within the development team, as everyone is working with a common set of guidelines.

**Comment by ManishBisht777** [comment]
I agree with you @Devansh-365 

do you want to work on it?

**Comment by Devansh-365** [comment]
Yeah sure

**Comment by ManishBisht777** [comment]
Assigned to you @Devansh-365
